// portal-os-v4/shell/index.ts

export const ShellViews = {
  DESKTOP: 'DESKTOP',
  SUITE_LAUNCHER: 'SUITE_LAUNCHER',
  SPORTS_DASHBOARD: 'SPORTS_DASHBOARD',
  IDENTITY_PANEL: 'IDENTITY_PANEL',
  PIPELINE_VIEWER: 'PIPELINE_VIEWER',
};
